repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v0.8.0
    hooks:
      - id: helm-docs
  - repo: git@github.com:Yelp/detect-secrets
    rev: v0.14.3
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*/tests/.*
